version: "3.8"

services:
  server:
    image: my_custom_api:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_KEY=${DB_KEY}
      - DB_URL=${DB_URL}
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server
    restart: unless-stopped
