version: "3.8"

services:
  my_service:
    image: nikhileshsingh/automated-security-scanning-devsecops:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_KEY=${DB_KEY:-S3cr3tIsThisYouKnowna}
      - DB_URL=${DB_URL:-mongodb+srv://harsh:harsh123@cluster0.poozi.mongodb.net/course_selling_app}
    restart: unless-stopped
    # Optional: Add volumes if you need data persistence
    # volumes:
    #   - ./data:/usr/src/app/data